---
- name: Install Docker
  ansible.builtin.include_tasks:
    file: install-docker.yml

- name: Install Traefik
  ansible.builtin.include_tasks:
    file: install-app.yml

- name: Kill all user sessions
  ansible.builtin.meta: reset_connection
