---
- name: Install apt packages
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items: '{{ apt_packages }}'
- name: Create directory for camera server
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: /opt/camera
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
- name: Copy camera server files
  ansible.builtin.copy:
    src: '{{ server_file }}'
    dest: /opt/camera
    remote_src: false
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
- name: Create virtual environment
  ansible.builtin.command:
    chdir: /opt/camera
    cmd: python3 -m venv /opt/camera/venv
- name: Install Python depedencies for camera
  ansible.builtin.pip:
    requirements: /opt/camera/flask-camera-server/requirements.txt
    virtualenv: /opt/camera/venv
- name: Change permissions for camera server
  ansible.builtin.file:
    path: /opt/camera/flask-camera-server/start-server.sh
    state: file
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
- name: Create systemd service for camera server
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.template:
    src: camera-server.service.j2
    dest: /etc/systemd/system/camera-server.service
    owner: root
    group: root
    mode: '0644'
  notify: Start camera service
