---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2

- name: Create directory for Docker's GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

# Could not get this to work.
#- name: Add Docker repo using key from URL.
#  ansible.builtin.deb822_repository:
#    name: docker
#    types: [deb]
#    uris: "https://download.docker.com/linux/ubuntu"
#    components: [stable]
#    #signed_by: /usr/share/keyrings/docker.gpg
#    signed_by: "https://download.docker.com/linux/ubuntu/gpg"
#    state: present
#    enabled: true

# Deprecated. see:
# https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system-key-is-stored-in-legacy-trust
# https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible
#- name: Add Docker GPG key
#  ansible.builtin.apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    keyring: /etc/apt/keyrings/docker.asc
#    state: present

# TODO why does the gather facts incorrectly report the architecture as x86_64?
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
          deb [arch={{ server_architecture }}
          signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  notify: Kill all user sessions

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service
