---
- name: Main server
  hosts: servers
  gather_facts: true
  become: true
  roles:
    - role: cv-server
- name: Raspberry Pi camera
  hosts: cameras
  gather_facts: true
  roles:
    - raspberrypi
    - camera
