version: "3.8"
services:
  traefik:
    image: "traefik"
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /opt/traefik
        target: "/etc/traefik"
    restart: unless-stopped
